<#
.SYNOPSIS
General mail template

.DESCRIPTION
This function sends mail based on file output generated by existing modules

.EXAMPLE
Start-GenerateMail -ModuleCustomIntegrityCheck -Verbose
Start-GenerateMail -ModuleCustomVMWare -Verbose
Start-GenerateMail -ModuleCustomAzure -Verbose

.NOTES
Function name:          Start-GenerateMail
Author:                 Dennis Kool
DateCreated:            14-08-2018
DateModified:           14-08-2018

.NOTES
14-08-2018:             Initial release
#>

Function Start-GenerateMail {


    [CmdletBinding()]
    param(
        [switch] $ModuleCustomIntegrityCheck,
        [switch] $ModuleCustomVMWare,
        [switch] $ModuleCustomAzure
    )

    #variable JSON file path is set in profile
    Write-Verbose "[$(Get-Date)] Loading data from JSON"
    $config = Get-Content `
        -Path $configfile `
        -Raw | ConvertFrom-Json

    if ($ModuleCustomVMWare) {
        Write-Verbose "[$(Get-Date)] Creating array with filenames for manifest module CustomVMWare"
        $file = @("$outputfolder\ShowAvailableVDIs\vmware-available-vdi-$((Get-Date).ToString('MM-dd-yyyy')).log",
            "$outputfolder\StartCompareVDIs\vmware-compare-vdi-$((Get-Date).ToString('MM-dd-yyyy')).log")
            
        Foreach ($entry in $file) {
            $existfile = Test-Path -Path $entry
            if ($existfile -eq "True") {
                Write-Verbose "[$(Get-Date)] $entry found. Sending mail"
                Send-MailMessage `
                    -To $config.mailto `
                    -from $config.mailfrom `
                    -Subject $config.mailsubject `
                    -Attachments $entry `
                    -Body "Expected file $entry found on server $env:COMPUTERNAME." `
                    -SmtpServer $config.smtpserver `
                    -Verbose
            }
            else {
                Write-Verbose "[$(Get-Date)] $entry not found. Sending mail"
                Send-MailMessage `
                    -To $config.mailto `
                    -from $config.mailfrom `
                    -Subject $config.mailsubject `
                    -Body "Expected file $entry not found on server $env:COMPUTERNAME. Please investigate" `
                    -SmtpServer $config.smtpserver `
                    -Verbose
            }
        
        }    

    }

    if ($ModuleCustomIntegrityCheck) {
        Write-Verbose "[$(Get-Date)] Creating array with filenames for manifest module CustomIntegrityCheck"
        $file = @("$outputfolder\StartIntegrityCheckADGroups\ad-creategroups-$((Get-Date).ToString('MM-dd-yyyy')).log")
    
        Foreach ($entry in $file) {
            $existfile = Test-Path -Path $entry
            if ($existfile -eq "True") {
                Write-Verbose "[$(Get-Date)] $entry found. Sending mail"
                Send-MailMessage `
                    -To $config.mailto `
                    -from $config.mailfrom `
                    -Subject $config.mailsubject `
                    -Attachments $entry `
                    -Body "Expected file $entry found on server $env:COMPUTERNAME." `
                    -SmtpServer $config.smtpserver `
                    -Verbose
            }
            else {
                Write-Verbose "[$(Get-Date)] $entry not found. Sending mail"
                Send-MailMessage `
                    -To $config.mailto `
                    -from $config.mailfrom `
                    -Subject $config.mailsubject `
                    -Body "Expected file $entry not found on server $env:COMPUTERNAME. Please investigate" `
                    -SmtpServer $config.smtpserver `
                    -Verbose
           
            }    
    
        }  

    }

    if ($ModuleCustomAzure) {
        Write-Verbose "[$(Get-Date)] Creating array with filenames for manifest module CustomAzure"
        $file = @("$outputfolder\ShowAzureBackups\azure-backups-$((Get-Date).ToString('MM-dd-yyyy')).log")
    
        Foreach ($entry in $file) {
            $existfile = Test-Path -Path $entry
            if ($existfile -eq "True") {
                Write-Verbose "[$(Get-Date)] $entry found. Sending mail"
                Send-MailMessage `
                    -To $config.mailto `
                    -from $config.mailfrom `
                    -Subject $config.mailsubject `
                    -Attachments $entry `
                    -Body "Expected file $entry found on server $env:COMPUTERNAME." `
                    -SmtpServer $config.smtpserver `
                    -Verbose
            }
            else {
                Write-Verbose "[$(Get-Date)] $entry not found. Sending mail"
                Send-MailMessage `
                    -To $config.mailto `
                    -from $config.mailfrom `
                    -Subject $config.mailsubject `
                    -Body "Expected file $entry not found on server $env:COMPUTERNAME. Please investigate" `
                    -SmtpServer $config.smtpserver `
                    -Verbose
           
            }    
    
        }  

    }

}
